apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ENTER_YOUR_ARN>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    service: n8n
  ports:
    - name: http
      port: 80
      targetPort: 5678
      protocol: TCP
    - name: https
      port: 443
      targetPort: 5678
      protocol: TCP
